### ISSUE TITLE
The `yourls.extraConfigContent` option is not used

### ISSUE THREAD

**Issue by inetshell** [YOURLS/charts#118]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

I wanted to use the yourls.extraConfigContent option, but it seems that the helm templates do not use it. I'm not sure if it was available before or if it's an error.

This is the line I'm referring to:
https://github.com/YOURLS/charts/blob/4d40d93d34b4a22cf2932f9bd17374cc6619ca45/charts/yourls/values.yaml#L126

### Expectation

I think this is a broken feature, as there is no code in the helm templates

### Reproduction steps

1. Create a values.yaml file
2. Set the yourls.extraConfigContent variable
3. Deploy yourls
4. Access the container and verify the content with `cat user/config.php`
5. The file won't include the extraConfigContent

### Context

The file "user/config.php" should include the content of the variable yourls.extraConfigContent

**Comment by AlfredoFloresV** [comment]
+1

**Comment by LuisGarcia88** [comment]
+1

**Comment by LeoColomb** [comment]
Thanks for your report, @inetshell.
Indeed, this value is not used currently and should probably be removed from the list.
Would you like to open a pull request?

@AlfredoFloresV @LuisGarcia88 Even if supporting a colleague is important, please don't ever comment with "+1". These kinds of comments brings no value, and are considered counterproductive if not harmful.
Use native reactions, they are here for that purpose.

**Comment by inetshell** [comment]
@LeoColomb is there a problem if I send a PR with a proposal to implement this feature? :)

**Comment by LeoColomb** [comment]
@inetshell There is no problem at all, you are welcome to send any PR!
But keep in mind we'll be quite strict on complexity addition and maintenance cost.
