### ISSUE TITLE
Incompatibility due to `kubeVersion`

### ISSUE THREAD

**Issue by masterkain** [YOURLS/charts#158]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

5.0.6

### Description

https://github.com/YOURLS/charts/blob/main/charts/yourls/Chart.yaml#L21

this line should not be there, or it needs to be modified:

`comparison failed: chart requires kubeVersion: ^1.20.0 which is incompatible with Kubernetes v1.21.9-eks-0d102a7`

**Comment by LeoColomb** [comment]
https://github.com/helm/helm/issues/3810
