### ISSUE TITLE
Container is using incorrect version

### ISSUE THREAD

**Issue by masterkain** [YOURLS/charts#160]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9

### Description

thanks for the fix in https://github.com/YOURLS/charts/issues/158

I installed the new chart version and I saw that `mariadb` is now being used, however in my value I use `externalDatabase` (mysql on aurora), so I just disabled `mariadb:` with `enabled: false`

upgrade went smoothly, I see the `ghcr.io/yourls/yourls:1.9` image running in kubernetes, however when visiting the `/admin/` page YOURLS says

- on top: `[YOURLS version 1.9](http://yourls.org/download) is available. Please update!`
- on bottom: Powered by [YOURLS](http://yourls.org/) v 1.8.2

so I'm a bit confused, following the docs there should not be much else to do but I see this version mismatch and I'm not sure if it's the chart, the database or the docker image.

any hint? thanks

**Comment by LeoColomb** [comment]
Thanks for opening this issue @masterkain.
That said please include more information about your deployment, like reproduction steps and the context.
So far the 1.9 image correctly includes the version 1.9 of YOURLS.

**Comment by masterkain** [comment]
is it possible that yourls just reads a version string from `yourls_options` table and it did not migrate values for some reason? I also tried running `/upgrade.php` to no avail.

<img width="490" alt="Screen Shot 2022-05-14 at 19 19 49" src="https://user-images.githubusercontent.com/12844/168442134-dcdebe9e-db99-4cf2-9018-cbb5504f7336.png">

I do not have repro steps (just upgraded chart from 4.2.22 to 5.0.7), the deployment is done via flux/helm but it's quite simple

**Comment by LeoColomb** [comment]
@masterkain It does not reflect a correct upgrade on database.
You should reach `admin/upgrade.php` to do so.

**Comment by masterkain** [comment]
hello,
thanks for the reply, however as I mentioned previously upgrade.php says that nothing should be done

it's not a big deal though, I can reimport the data in a new database

cheers
