### ISSUE TITLE
persistence.enabled=false fails 

### ISSUE THREAD

**Issue by sigmonsays** [YOURLS/charts#2]
**Describe the bug**

mariadb fails to start without persistence

logs on yourls-mariadb-0 pod say
`mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied`

**To Reproduce**
1. create values.yaml
<pre>
persistence:
  enabled: false
</pre>
2. helm install 
<pre>
helm install --name yourls yourls/yourls -f values.yaml
</pre>
**Expected behavior**

components should start without error

**Actual behavior**

permission failures. see above

**Versions**
helm chart version yourls-1.1.2

**Comment by LeoColomb** [comment]
Thanks for opening this issue @sigmonsays!

That said your output is really strange, I mean MariaDB persistance should not inherit from YOURLS chart persistance variable.
Actually MariaDB have [its own namespace](https://github.com/YOURLS/charts/blob/8a49e2b80098ff630aed191241358cca3ead2676/charts/yourls/values.yaml#L70-L99).

Also, the output indicates a permission issue, which AFAIK has nothing to do with persistence...

Is it possible to investigate further on your side? Thanks! 🙂

**Comment by sigmonsays** [comment]
New to helm, It is not clear to me that persistence.enabled=false doesn't also configure mariadb. So I need to provide values to also configure mariadb?

**Comment by sigmonsays** [comment]
I have tried to configure the mariadb server but it doesn't come up with installing with helm install yourls. Can you share an example values.yaml for bringing up a mysql server in helms values.yaml?

**Comment by LeoColomb** [comment]
@sigmonsays You can try the following:

```yaml
mariadb:
  persistence:
    enabled: true
```

But please not disabling persistence will transform any update to a data destroyer. 
And again, the output indicates a permission issue, which AFAIK has nothing to do with persistence...

**Comment by LeoColomb** [comment]
@sigmonsays Did you find something?

**Comment by LeoColomb** [comment]
Resolved by https://github.com/YOURLS/charts/commit/895655adc10a6d3e4d719b4cb90b24f42feefb48
