### ISSUE TITLE
Ingress `extraHosts` does not allow different backend

### ISSUE THREAD

**Issue by unacceptable** [YOURLS/charts#213]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

For the ingress backend, I would like to be able to specify `serviceName` and `servicePort`.

### Motivation

As an SRE, I don't want someone to try to ClickOps an upgrade in the UI.  We should have the ability to block certain admin paths.

### Describe the solution

I will put in a PR this afternoon.

**Comment by unacceptable** [comment]
https://github.com/YOURLS/charts/pull/215 created.

**Comment by LeoColomb** [comment]
> I would like to be able to specify serviceName and servicePort.

As discussed in #215, it should be possible already.

```yaml
extraHosts:
  - name: yourls.local
    serviceName: name
    servicePort: port
    ...
```
