### ISSUE TITLE
CORS errror when exposing app via Ingress

### ISSUE THREAD

**Issue by byakku** [YOURLS/charts#26]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
CORS Error - Missing Allow Origin

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. Install helm chart
2. Expose service through ingress (Traefik 2.x <-> AWS Loadbalancer), add CNAME in DNS
3. Set up app, try to create link 
4. In network tab `CORS Missing Allow Origin` error will appear, nothing will happen

**Expected behavior**
Being able to create a link.

**Actual behavior**
CORS Error

**Screenshots**

**Versions**
Tag 1.7.9 official docker image

**Additional context**
AWS, Classic LB, Traefik as ingress, DNS entry as CNAME.

[CORS plugin ](https://github.com/TEODE/yourls-access-control-allow-origin) does not change anything, adding extra headers in .htaccess does not change app's behaviour too. [yourls-allow-aliases](https://github.com/adigitalife/yourls-allow-aliases) results in empty error during activation:

```
Plugin generated unexpected output. Error was: 
```

Debug mode enabled does not show anything related to this in logs. 

Additionally, not everything seems to be hosted via HTTPs, but that's other issue.

Any ideas how to approach this problem from app's side?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @byakku.

Would you be able to check the HTTP Header sent by Traefik?

> not everything seems to be hosted via HTTPs, but that's other issue

Maybe not another issue...

**Comment by byakku** [comment]
Headers in the request
```
GET
Host: yourls.mydomain.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: https://yourls.mydomain.com
Connection: keep-alive
Sec-GPC: 1
```

Log
```
yourls-yourls-5bdbdc459c-g8vjv yourls-yourls 10.50.86.136 - - [28/Jan/2021:10:01:45 +0000] "GET /admin/admin-ajax.php?action=add&url=https%3A%2F%2Fstallman.org&keyword=gentoo&nonce=53695cc7ee HTTP/1.1" 200 1371 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

**Comment by LeoColomb** [comment]
@byakku Sorry for the late answer. I'm thinking about this everyday but I don't have any concrete idea.
Only think we can try is switching ingress to Nginx engine to see if this affect the result.
