### ISSUE TITLE
Breaking Changes in minor release (1.4.1)

### ISSUE THREAD

**Issue by morremeyer** [YOURLS/charts#28]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
The minor release bump from 1.3.2 to 1.4.1 contains breaking changes: 

* mariadb was replaced by MySQL
* breaking changes in values file were made

**To Reproduce**
1. Try to upgrade from 1.3.2 to 1.4.1 without changing existing values.

**Expected behavior**
Major version bump on breaking changes (to 2.0.0 in this case)

**Actual behavior**
Minor version change is breaking

**Comment by morremeyer** [comment]
I propose to retract the 1.4.1 release, bump the version to 2.0.0 and release it again. I can take care of the necessary changes if you agree.

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @morremeyer!
Indeed I've change quite a lot the API, major version bump might be better.
The breaking change actually comes with 1.4.0.

> I can take care of the necessary changes if you agree.

With pleasure!

**Comment by morremeyer** [comment]
@LeoColomb Cool, I opened #29 to do that. What do you think about retracting 1.4.0 and 1.4.1 after 2.0.0 is released?

**Comment by LeoColomb** [comment]
> retracting 1.4.0 and 1.4.1

Let's try. 🙂

**Comment by LeoColomb** [comment]
Should be good now.

**Comment by morremeyer** [comment]
LGTM, thank you!
