### ISSUE TITLE
Use Bitnami Mariadb chart instead of deprecated Mariadb chart

### ISSUE THREAD

**Issue by KrustyHack** [YOURLS/charts#5]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

```
Release "yourls" does not exist. Installing it now.
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"
```

**To Reproduce**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

1. `helm upgrade --install yourls --namespace yourls yourls/yourls`

**Expected behavior**
Chart installed correctly

**Actual behavior**

apiVersion is not correct.

Mariadb stable chart is not deprecated in favor of Btnami Mariadb which fix the apiVersion error too : https://github.com/bitnami/charts/blob/master/bitnami/mariadb/templates/_helpers.tpl#L4

**Comment by LeoColomb** [comment]
Thanks for this ticket @KrustyHack, good catch!

Would you like to open a pull request with Bitnami chart ref instead?

**Comment by KrustyHack** [comment]
Ay,

Yes, I will do that asap and test it.
