### ISSUE TITLE
Can't upgrade from 3.x to 4.x using `yourls.passwordExistingSecret`.

### ISSUE THREAD

**Issue by rjhenry** [YOURLS/charts#75]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

Upgrading from the latest 3.x.y release to 4.0.4 fails, with the following messages from Helm:
```
Last Helm logs:

preparing upgrade for yourls
resetting values to the chart's original version
  Normal  error  67s (x8 over 71s)  helm-controller  reconciliation failed: Helm upgrade failed: execution error at (yourls/templates/NOTES.txt:107:4): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'yourls.password' must not be empty, please add '--set yourls.password=$YOURLS_PASSWORD' to the command. To get the current value:

        export YOURLS_PASSWORD=$(kubectl get secret --namespace "gosubme" yourls -o jsonpath="{.data.yourls-password}" | base64 --decode)
  Normal  info  66s (x9 over 71s)  helm-controller  Helm upgrade has started
```

There's also no documentation in the repository to state that this is needed - it's only in the `NOTES.txt` file.

### Expectation

Helm upgrade should succeed without needing the secret to be specified in plaintext, as there's a mechanism to fetch the value from secrets.

### Reproduction steps

Install 4.x.y using `yourls.passwordExistingSecret` instead of `yourls.password`

### Context

Helm releases managed by Weave Flux.

**Comment by LeoColomb** [comment]
Thanks for opening this case @rjhenry.

> Install 4.x.y using `yourls.passwordExistingSecret` instead of `yourls.password`

Indeed, with version 4, you should use `yourls.existingSecret`.
Could you try with this instead?

**Comment by LeoColomb** [comment]
Thanks for this lines, just updated the 4.0.0 release note to include them.
Apologies for these big changes, it has been the only way for me to simplify a lot the maintenance cost (as using bitnami common chart as a base).

> * When `yourls.scheme` is set to HTTPS, readiness checks fail (may be a separate issue)

👍 for another issue.

**Comment by rjhenry** [comment]
Hi Leo - thanks, that's great. Where abouts in the release notes would I be looking? I'm taking a look over both the git repo and the Artifact hub and can't see any notes. Either way, if there's some documentation that should be fine.
Definitely a sensible move to move to an easier-to-maintain chart!

> +1 for another issue.
I'll collect a little more depth and create a fresh issue for this.

Thanks for all the hard work you put into this excellent product - feel free to close off this issue once you lead the blind to the documentation.

**Comment by LeoColomb** [comment]
You can find it here: https://github.com/YOURLS/charts/releases/tag/yourls-4.0.0
It should appear on the Artifact Hub soon as well.

Plus, I've improved the values schema significantly, almost all values should have at least type validation.
