### ISSUE TITLE
https://charts.yourls.org/ is a 404

### ISSUE THREAD

**Issue by ozh** [YOURLS/charts#8]
@LeoColomb is something missing? Not sure what you had in mind

**Comment by LeoColomb** [comment]
@ozh `charts.yourls.org` is a helm repo, not a real website.

* https://charts.yourls.org/index.yaml
* https://github.com/YOURLS/charts/tree/gh-pages

**Comment by ozh** [comment]
Oh, I see. So, just missing an index.html with "duh, not a real website, just a helm repo" for dummies like me? :)

**Comment by LeoColomb** [comment]
There is no reason to access the domain at the root directly, but there is now [a homepage](https://charts.yourls.org/). 😃

**Comment by ozh** [comment]
❤️
